---
deployment:
 tasks:
 - export DEPLOYPATH=/home4/interxec/public_html/essgeelabs/
 - /bin/rm -r $DEPLOYPATH/css 
 - /bin/rm -r $DEPLOYPATH/js 
 - /bin/rm -r $DEPLOYPATH/img
 - /bin/rm -r $DEPLOYPATH/categories
 - /bin/rm -r $DEPLOYPATH/page
 - /bin/rm -r $DEPLOYPATH/posts
 - /bin/rm -r $DEPLOYPATH/tags
 - /bin/rm $DEPLOYPATH/style.css
 - /bin/cp -Rf about $DEPLOYPATH
 - /bin/cp -Rf archives $DEPLOYPATH
 - /bin/cp -Rf assets $DEPLOYPATH
 - /bin/cp -Rf categories $DEPLOYPATH
 - /bin/cp -Rf images $DEPLOYPATH
 - /bin/cp -Rf page $DEPLOYPATH
 - /bin/cp -Rf posts $DEPLOYPATH
 - /bin/cp -Rf search $DEPLOYPATH
 - /bin/cp -Rf tags $DEPLOYPATH
 - /bin/cp 404.html $DEPLOYPATH
 - /bin/cp favicon-16x16.png $DEPLOYPATH
 - /bin/cp favicon-32x32.png $DEPLOYPATH
 - /bin/cp favicon.ico $DEPLOYPATH
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp index.json $DEPLOYPATH
 - /bin/cp index.xml $DEPLOYPATH
 - /bin/cp robots.txt $DEPLOYPATH
 - /bin/cp sitemap.xml $DEPLOYPATH
